platform :ios, '9.0'
inhibit_all_warnings!
#use_frameworks!

target :NoWait do

    # --------------------- 第三方Pod -----------------------
    pod 'AFNetworking', '~> 3.1.0'
    pod 'SDWebImage', '~> 3.7'
    pod 'Masonry', '~> 1.1.0'
    pod 'MJRefresh', '~> 3.1.15'
    pod 'MJExtension', '~> 3.0.13'
    pod 'FMDB', '~> 2.7.2'
    pod 'ReactiveCocoa', '~> 2.5'
    pod 'CocoaLumberjack', '~> 3.3.0'
    pod 'YYKit'
    pod 'WXSTransition'
    pod 'SDCycleScrollView'
    pod 'WMPageController'
    pod 'BlocksKit'
    pod 'DZNEmptyDataSet'
    pod 'IQKeyboardManager'
    pod 'DACircularProgress'
    pod 'MBProgressHUD'
    pod 'SJVideoPlayer'


#    pod 'pop', '~> 1.0'

end

