source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
inhibit_all_warnings!
#use_frameworks!

target :NoWait do

    # --------------------- 第三方Pod -----------------------
    pod 'AFNetworking', '~> 3.1.0'
    pod 'SDWebImage', '~> 3.7'
    pod 'Masonry', '~> 1.1.0'
    pod 'MJRefresh', '~> 3.1.15'
    pod 'MJExtension', '~> 3.0.13'
    pod 'FMDB', '~> 2.7.2'
    pod 'ReactiveCocoa', '~> 2.5'
    pod 'CocoaLumberjack', '~> 3.3.0'
    pod 'YYKit'
    pod 'WXSTransition'
    pod 'SDCycleScrollView'
    pod 'WMPageController'
    pod 'BlocksKit'
    pod 'DZNEmptyDataSet'
    pod 'IQKeyboardManager'
    pod 'DACircularProgress'
    pod 'MBProgressHUD'
    pod 'SJVideoPlayer'
    pod 'SJBaseVideoPlayer', :git => 'https://github.com/changsanjiang/SJBaseVideoPlayer.git'


# 全能tabBarController
    pod 'TLTabBarController', :git => 'https://github.com/tbl00c/TLTabBarController.git', :tag => '0.0.6'
    pod 'ZZFLEX', :git => 'https://github.com/tbl00c/ZZFLEX.git', :tag => '0.0.6'


    pod 'TLKit', :git => 'https://github.com/tbl00c/TLKit.git', :tag => '0.0.27'

    pod 'PGPickerView'
    pod 'AMap2DMap'
    pod 'AMapLocation'
    pod 'AMapSearch'
#    pod 'pop', '~> 1.0'
#umeng
    pod 'UMCCommon'
    pod 'UMCSecurityPlugins'
    pod 'UMCAnalytics'

 # U-Share SDK UI模块（分享面板，建议添加）
    pod 'UMCShare/UI'
#    pod 'AlipaySDK-iOS'

# 集成微信(精简版0.2M)
    pod 'UMCShare/Social/ReducedWeChat'
    pod 'WechatOpenSDK'

end
